name: nuniyoekyc
description: Nuniyo EKYC Module

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.13
  material_design_icons_flutter: ^4.0.5955
  url_launcher: ^6.0.9
  intl_phone_field: ^2.0.1
  file_picker: ^3.0.4

  shared_preferences: 0.5.6
  http: ^0.13.3
  expandable: ^5.0.1
  image_picker: ^0.8.3+2
  video_player: ^2.1.13
  dio: ^4.0.0
  geolocator: ^7.4.0
  fluttertoast: ^8.0.8
  geocoder: ^0.2.1
  local_auth: ^1.1.0
  syncfusion_flutter_signaturepad: ^19.2.56
  baseflow_plugin_template:
    git:
      url: git://github.com/Baseflow/baseflow_plugin_template.git
      ref: v2.1.0
  permission_handler: ^8.1.4+2
  google_fonts: ^2.1.0
  razorpay_flutter:

  get_ip_address:
  device_info_plus: ^2.1.0
  sim_info: ^0.1.3
  path_provider: ^2.0.3
  camera: ^0.9.2+2
  #camera: ^0.8.1
  dotted_border: ^2.0.0+1
  image_cropper: ^1.4.1
  webviewx: ^0.2.1
  get: ^4.3.8
  syncfusion_flutter_pdfviewer: ^19.2.62-beta
  flushbar: ^1.10.4
  email_validator: ^2.0.1
  syncfusion_flutter_datepicker: ^19.2.62
  flutter_svg: ^0.22.0
  otp_autofill: ^1.1.0
  flutter_icons: ^1.1.0
  video_compress: ^3.1.0

  downloads_path_provider: ^0.1.0
  open_file: ^3.2.1
  flutter_image_compress: ^1.1.0
  floating_action_bubble: ^1.1.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  razorpay_flutter:

  flutter_launcher_icons:

flutter_icons:
  image_path: "assets/images/mklogoicon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NuniyoCustomIcons
      fonts:
        - asset: assets/icons/NuniyoCustomIcons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
